               <h1>Blog</h1>
                <div class="container">
                    
                    <?php foreach($res as $post){ ?>
                    <div class="card" >
                    <div class="card-body" >
                        
                            <div class="homeArt">
                               <?php if(!empty($post['url'])){ ?>
                                <img src="image/<?= $post['url'] ?>" class="card-img-top" alt="">

                               <?php } else { ?>
                                <img src="image/replace.jpg"  alt="">

                               <?php } ?>

                                <p class="card-text" id="temp"><?= $post['date_post'] ?></p>
                            </div>
                            <div>
                                <table>
                                    <tr>
                                        <td> <a href="comment.php?id=<?= $post['id'] ?>" ><h2 class="card-title"><?= $post['titre'] ?>  </h2></a></td>
                                        <td><a href="author_select_post.php?post_id=<?= $post['id'] ?>"><i class="fas fa-pen-square fa-2x" title="Update"></i></a></td>
                                        <td><a href="author_delete_post.php?post_id=<?= $post['id'] ?>"><i class="fas fa-trash-alt fa-2x " title="Delete"></i></a></td>
                                    </tr>
                                </table>                               
                                                               
                                <p class="card-text"><?= $post['contenu'] ?></p>
                                
                                <p class="card-text" id="aut">Author : <?= $post['auteur'] ?></p>
                                
                                <p class="card-text" id="cat">Category : <?= $post['nom'] ?></p>

                            </div>
                            
                        </div>
                       </div>
                    <?php } ?>
                          
                </div>
