<link rel="stylesheet" href="css/inscri.css">
    <form method="post" action="insert_inscri_author.php">
            <h1>FORMULAIRE D'INSCRIPTION AUTEUR</h1>

                <div class="container">

                    <div class="panel-heading">
                        <div style="float:right;">Vous avez un compte!  <a id="signinlink" href="insertlogin.php">Se connecter</a></div>
                    </div>
                <br>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <input type="text" name="prenom"
                            class="form-control" placeholder="First name">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <input type="text"  name="nom"
                            class="form-control" placeholder="Last name">
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <div class="col-md-6">
                            <label for="inputEmail4">Email</label>
                            <input type="email" name="mail" class="form-control" id="inputEmail4" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <label for="inputPassword4">Password</label>
                            <input type="password" class="form-control" name="pass" id="inputPassword4" placeholder="Password">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Sign in</button>
                </div>
            </form>
      