<link rel="stylesheet" href="css/log.css">
            <h1>Connexion</h1>
            <form method="post" action="insertlogin.php">
                <div class="container">
                  <div class="panel-heading">
                        <div style="float:right;"> 
                          Vous n'avez pas de compte? <a href="insert_inscri.php">Inscrivez vous maintenant!</a>
                        </div>
                  </div>
                  <h4>Welcome back</h4>
                    <div class="form-group col-md-6">
                        <label>Mail address</label>
                        <input type="email" class="form-control" name="mail" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
                    </div>
                    <div class="form-group col-md-6">
                        <label>Password</label>
                        <input type="password" name="pass" class="form-control" id="exampleInputPassword1" placeholder="Password">
                    </div>

                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form> 

