            <h1>Add post</h1>

            <form  id="formulaire" method="POST" action="postadd.php" enctype="multipart/form-data">
                <div class="container">
                    <div class="row">

                    <!-- Post Content Column -->
                        <div class="col-lg-8">
                            <!-- Title -->
                            <label>Title</label>
                            <input type="text" class="form-control" name="title" id="title">

                            <hr>                           <!-- Cateory -->
                            <label>Category</label>
                            <select name="category" class="form-control">
                            <?php foreach($cat as $row) { ?>
                            <option value="<?php echo  $row->id ?>"><?php echo $row->nom ?></option>
                            <?php } ?>

                            </select>
                            <hr>

                            <!-- content -->
                            <label>Contents</label>
                            <textarea name="content" id="content" cols="30" rows="10" class="form-control"></textarea>   

                            <hr>
                            <!-- Preview Image -->
                            <label>Image :</label>
                            <input type="file" name="image" size="30" class="form-control"/>


                            <hr>

                        </div>
                    </div>
                <!-- /.row -->
                <input type="submit" value="Add Post" class="btn btn-info"/>
                </div>
            </form>
